### ISSUE TITLE
Launching Failed, "Failed to create Java Virtual Machiene"

### ISSUE THREAD

**Issue by iSuperFuryX** [ShonP40/CheatBreaker-Modpack#2]
Once I installed the launcher and it finished downloaded everything it tried launching and then gave me an error popup with this as the error. https://pastebin.com/upTQDmJa 

The game is running. Please Wait.
Error: Could not create the Java Virtual machine
Error: A fatal exception has occurred. Program will exit
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum re presentable size
Process ended with code: 1

**Comment by ShonP40** [comment]
How much RAM does your PC have?

**Comment by iSuperFuryX** [comment]
> How much RAM does your PC have?

16.0 GB

**Comment by ShonP40** [comment]
Did you install Java 32 bit or 64 bit?

**Comment by iSuperFuryX** [comment]
> Did you install Java 32 bit or 64 bit?

Pretty Sure it was Java 64-bit.

**Comment by ShonP40** [comment]
```Invalid` maximum heap size: -Xmx4096M``` means that Java doesn't see that you have 4 GB of RAM available.

That can be caused because you have a 32 Bit version of Java installed or you don't have 4 GB of RAM available at the moment.

**Comment by iSuperFuryX** [comment]
I will check lol.

**Comment by ShonP40** [comment]
Are you using Windows?

**Comment by iSuperFuryX** [comment]
It says I have 10GB left of ram, and yes i am using windows 10

**Comment by ShonP40** [comment]
Type `Java` in the Windows search bar and click on `Configure Java` , then click on the `Java` tab and then click on `view`.

Under architecture, does it say `x86` or `x86_64` ?

**Comment by iSuperFuryX** [comment]
x86

**Comment by ShonP40** [comment]
That means that you have Java 32 Bit installed

**Comment by iSuperFuryX** [comment]
Oh my bad, I don't know why it has 32 bit. Appreciate it! I'll go download 64bit and see if it works.

**Comment by ShonP40** [comment]
You can't use 4 GB of RAM or more with 32 Bit Java.

**Comment by ShonP40** [comment]
You can just change the max ram amount to 2 GB of ram by:

1. Open the launcher
2. Click on `Options`.
3. Set the `Maximum memory (MB):` to `2048`.
4. Click OK.
